language: python
python: 3.6
env:
  - HUGO_VERSION=0.53

branches:
  only:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo
  - pip install pygments
  - git submodule update --remote

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
